### ISSUE TITLE
linux installation: gtk-query-immodules-3.0

### ISSUE THREAD

**Issue by sgyetvay** [conda-forge/graph-tool-feedstock#66] opened 2021-09-30 21:19 UTC
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>

hi

i ran into the following issue while installing graph-tool on a linux server 

after running 

`conda create --name gt -c conda-forge graph-tool`

i received the message

```
anaconda3/envs/gt/bin/gtk-query-immodules-3.0: error while loading shared libraries:
libXcursor.so.1: cannot open shared object file: No such file or directory
ERROR: Failed to complete gtk3's post-link script.
To fix this, activate the environment and run:
    glib-compile-schemas "/home/anaconda3/envs/gt/share/glib-2.0/schemas"
    gtk-update-icon-cache -f -t "/home/anaconda3/envs/gt/share/icons/hicolor"
    gtk-query-immodules-3.0 --update-cache
```

unfortunately running the three suggested lines gives another error

`gtk-query-immodules-3.0: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory`

i did not get the same error when i installed `graph-tool-base`, so i think the issue is with one of the extraneous dependencies

**Comment by stuarteberg** [comment] 2021-10-01 02:36
The issue you're seeing has been encountered before; see the [workaround described here][1].

**Explanation:** Gtk (and therefore graph-tool) requires X11 libraries to be installed on your machine.  If they aren't already installed via your OS package manage, then you can install them from conda-forge.

[1]: https://github.com/conda-forge/graph-tool-feedstock/issues/27#issuecomment-659321036

**Comment by stuarteberg** [comment] 2022-06-09 15:01
Duplicate of #29

**Closed by stuarteberg** 2022-06-09 15:01 UTC
